name: medusa-env
channels:
  - bioconda
  - defaults
  - conda-forge
  - benschneider
dependencies:
  - python
  - biopython
  - sh
  - perl
  - gcc
  - gawk
  - sed
  - fig2dev
  - gnuplot
  - xfig
  - networkx




 
